name: poking around
on:
  push:
    branches: [ check-actions ]

jobs:
  pokehaskell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2.7.1
        with:
          ghc-version: '9.8.2'
          cabal-version: '3.10'
            
      - name: poke
        run: |
          which ghc
          which cabal
          cabal update -v
          cabal build -v --only-dependencies